# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barts Tech Blog
email: bartdailey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site for documenting my journey from a skilled tradesman (machinist) to a 
  Web Developer. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bartstech.com" # the base hostname & protocol for your site
twitter_username: daileybart
github_username:  BartDailey

# Build settings
markdown: kramdown
